{{- if .Values.operatorConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator.configname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ required "operatorConfig is required" .Values.operatorConfig | nindent 4 }}
{{- end }}
